export const LOGOUT = 'LOGOUT';

export const LOGIN = 'LOGIN';
export const LOGIN_LOADING = 'LOGIN_LOADING';

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_USER_LOADING = 'SIGN_UP_USER_LOADING';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_LOADING = 'FORGOT_PASSWORD_LOADING';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CHANGE_AUTH_STATUS = 'CHANGE_AUTH_STATUS';

export const SET_TIMEOUT_ID = 'SET_TIMEOUT_ID';
export const CLEAR_TIMEOUT_ID = 'CLEAR_TIMEOUT_ID';
export const SET_LOGOUT_STATUS = 'SET_LOGOUT_STATUS';
export const SET_LOGOUT_TIME = 'SET_LOGOUT_TIME';
export const ONLINE_USERS = 'ONLINE_USERS';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE = 'UPDATE';
export const SETUSER = 'SETUSER';

export const VERIFY_EMAIL_ADDRESS = 'VERIFY_EMAIL_ADDRESS';
export const VERIFY_EMAIL_ADDRESS_LOADING = 'VERIFY_EMAIL_ADDRESS_LOADING';

export const RESEND_VERIFICATION_EMAIL = 'RESEND_VERIFICATION_EMAIL';
export const RESEND_VERIFICATION_EMAIL_LOADING = 'RESEND_VERIFICATION_EMAIL_LOADING';

export const GET_USER = 'GET_USER';
export const GET_USER_LOADING = 'GET_USER_LOADING';

export const SET_FOLLOWING = 'SET_FOLLOWING';

export const AFFILIATE = 'AFFILIATE';
