export const CREATE_NFT = 'CREATE_NFT';
export const CREATE_NFT_LOADING = 'CREATE_NFT_LOADING';
export const TOP_NFTS = 'TOP_NFTS';
export const LOADING = 'LOADING';

export const LIST_NFT_ON_MARKETE = 'LIST_NFT_ON_MARKETE';
export const LIST_NFT_ON_MARKETE_LOADING = 'LIST_NFT_ON_MARKETE_LOADING';

export const GET_MARKETE_PLACE = 'GET_MARKETE_PLACE';
export const GET_MARKETE_PLACE_LOADING = 'GET_MARKETE_PLACE_LOADING';
export const GET_MARKETE_PLACE_FROM_LOADING = 'GET_MARKETE_PLACE_FROM_LOADING';

export const GET_NFT_BY_ID = 'GET_NFT_BY_ID';
export const GET_NFT_BY_ID_LOADING = 'GET_NFT_BY_ID_LOADING';

export const UPDATE_NFT_BY_ID = 'UPDATE_NFT_BY_ID';
export const UPDATE_NFT_BY_ID_LOADING = 'UPDATE_NFT_BY_ID_LOADING';

export const GET_LISTINGS = 'GET_LISTINGS';
export const GET_LISTINGS_LOADING = 'GET_LISTINGS_LOADING';

export const PLACE_BID = 'PLACE_BID';
export const PLACE_BID_LOADING = 'PLACE_BID_LOADING';

export const INSERT_BID = 'INSERT_BID';

export const BUY_NFT = 'BUY_NFT';
export const BUY_NFT_LOADING = 'BUY_NFT_LOADING';

export const GET_ACTIVE_BIDDINGS = 'GET_ACTIVE_BIDDINGS';
export const GET_ACTIVE_BIDDINGS_LOADING = 'GET_ACTIVE_BIDDINGS_LOADING';

export const CLAIM_NFT_LOADING = 'CLAIM_NFT_LOADING';
export const CLAIM_NFT_LOADING_LOADING = 'CLAIM_NFT_LOADING_LOADING';

export const UNLIST_NFT_LOADING = 'UNLIST_NFT_LOADING';
export const UNLIST_NFT_LOADING_LOADING = 'UNLIST_NFT_LOADING_LOADING';

export const GET_LISTING_BY_LISTING_ID = 'GET_LISTING_BY_LISTING_ID';
export const GET_LISTING_BY_LISTING_ID_LOADING = 'GET_LISTING_BY_LISTING_ID_LOADING';

export const GET_NFT_BY_TOKEN_ID = 'GET_NFT_BY_TOKEN_ID';
export const GET_NFT_BY_TOKEN_ID_LOADING = 'GET_NFT_BY_TOKEN_ID_LOADING';

export const GET_BIDS_BY_LISTING_ID = 'GET_BIDS_BY_LISTING_ID';
export const GET_BIDS_BY_LISTING_ID_LOADING = 'GET_BIDS_BY_LISTING_ID_LOADING';

export const GET_OWNER_BY_WALLET_ADDRESS = 'GET_OWNER_BY_WALLET_ADDRESS';
export const GET_OWNER_BY_WALLET_ADDRESS_LOADING = 'GET_OWNER_BY_WALLET_ADDRESS_LOADING';

export const GET_AUCTION_NFT = 'GET_AUCTION_NFT';
export const GET_AUCTION_NFT_LOADING = 'GET_AUCTION_NFT_LOADING';

export const GET_TOP_NFT = 'GET_TOP_NFT';
export const GET_TOP_NFT_LOADING = 'GET_TOP_NFT_LOADING';

export const CREATE_REPORT = 'CREATE_REPORT';
export const CREATE_REPORT_LOADING = 'CREATE_REPORT_LOADING';

export const GET_LISTINGS_LOCAL = 'GET_LISTINGS_LOCAL';
export const GET_LISTINGS_LOADING_LOCAL = 'GET_LISTINGS_LOADING_LOCAL';

export const GET_USDT_USD_PRICE = 'GET_USDT_USD_PRICE';
export const GET_USDT_USD_PRICE_LOADING = 'GET_USDT_USD_PRICE_LOADING';

export const GET_LOOBR_USD_PRICE = 'GET_LOOBR_USD_PRICE';
export const GET_LOOBR_USD_PRICE_LOADING = 'GET_LOOBR_USD_PRICE_LOADING';

export const GET_BNB_PRICE = 'GET_BNB_PRICE';
export const GET_BNB_PRICE_LOADING = 'GET_BNB_PRICE_LOADING';

export const GET_ETH_PRICE = 'GET_ETH_PRICE';
export const GET_ETH_PRICE_LOADING = 'GET_ETH_PRICE_LOADING';

export const GET_AVAX_PRICE = 'GET_AVAX_PRICE';
export const GET_AVAX_PRICE_LOADING = 'GET_AVAX_PRICE_LOADING';

export const GET_CURRENCY_RATE = 'GET_CURRENCY_RATE';
export const GET_CURRENCY_RATE_LOADING = 'GET_CURRENCY_RATE_LOADING';

export const GET_NFT_HISTORY = 'GET_NFT_HISTORY';
export const GET_NFT_HISTORY_LOADING = 'GET_NFT_HISTORY_LOADING';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_BY_ID_LOADING = 'GET_USER_BY_ID_LOADING';

export const GET_NFT_CREATOR = 'GET_NFT_CREATOR';
export const GET_NFT_CREATOR_LOADING = 'GET_NFT_CREATOR_LOADING';

export const GET_ROYALTY_INFO = 'GET_ROYALTY_INFO';
export const GET_ROYALTY_INFO_LOADING = 'GET_ROYALTY_INFO_LOADING';

export const SET_ROYALTIES = 'SET_ROYALTIES';
export const SET_ROYALTIES_LOADING = 'SET_ROYALTIES_LOADING';

export const SEND_GIFT = 'SEND_GIFT';
export const SEND_GIFT_LOADING = 'SEND_GIFT_LOADING';

export const GET_MATIC_PRICE = 'GET_MATIC_PRICE';
export const GET_MATIC_PRICE_LOADING = 'GET_MATIC_PRICE_LOADING';
