export const GET_NFT = 'GET_NFT';
export const GET_NFT_LOADING = 'GET_NFT_LOADING';

export const CREATE_WALLET = 'CREATE_WALLET';
export const CREATE_WALLET_LOADING = 'CREATE_WALLET_LOADING';

export const GET_TOP_USERS = 'GET_TOP_USERS';
export const GET_TOP_USERS_LOADING = 'GET_TOP_USERS_LOADING';

export const LOADING = 'LOADING';
export const GET_FEED = 'GET_FEED';
export const CREATE_FEED = 'CREATE_FEED';
export const LOADING_CREATE_FEED = 'LOADING_CREATE_FEED';
export const LOADING_POST_COMMENT = 'LOADING_POST_COMMENT';
export const POST_COMMENT = 'POST_COMMENT';
export const POST_LIKE = 'POST_LIKE';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_LOADING = 'GET_ALL_USERS_LOADING';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const GET_USER_BY_ID_LOADING = 'GET_USER_BY_ID_LOADING';

export const POST_DELETE = 'POST_DELETE';
export const POST_DELETE_LOADING = 'POST_DELETE_LOADING';

export const COMMENT_DELETE = 'COMMENT_DELETE';
export const COMMENT_DELETE_LOADING = 'COMMENT_DELETE_LOADING';

export const GET_LOOBR_SCORE = 'GET_LOOBR_SCORE';
export const GET_LOOBR_SCORE_LOADING = 'GET_LOOBR_SCORE_LOADING';

export const GET_RECENTLY_REGISTERED_USERS = 'GET_RECENTLY_REGISTERED_USERS';
export const GET_RECENTLY_REGISTERED_USERS_LOADING = 'GET_RECENTLY_REGISTERED_USERS_LOADING';

export const GET_USER_STATS = 'GET_USER_STATS';
export const GET_USER_STATS_LOADING = 'GET_USER_STATS_LOADING';

export const CHANGE_2FA_STATUS = 'CHANGE_2FA_STATUS';
export const CHANGE_2FA_STATUS_LOADING = 'CHANGE_2FA_STATUS_LOADING';

export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';

export const SELECT_POLL = 'SELECT_POLL';
export const SELECT_POLL_LOADING = 'SELECT_POLL_LOADING';
