export const GET_TOPLANDOWNERS = 'GET_TOPLANDOWNERS';
export const GET_TOPISLANDOWNERS = 'GET_TOPISLANDOWNERS';
export const GET_TOPONEISLANDOWNERS = 'GET_TOPONEISLANDOWNERS';
export const GET_LANDS = 'GET_LANDS';
export const GET_ISLANDS = 'GET_ISLANDS';
export const LOADING = 'LOADING';
export const GET_ALL_LISTINGS = 'GET_ALL_LISTINGS';
export const GET_MY_LANDS = 'GET_MY_LANDS';
export const GET_ISLAND_OWNERS = 'GET_ISLAND_OWNERS';

// export const GET_TOPISLANDOWNERS = 'GET_TOPISLANDOWNERS';
// export const GET_TOPISLANDOWNERS = 'GET_TOPISLANDOWNERS';
