export const GET_ALL_COLLECTIONS = "GET_ALL_COLLECTIONS";
export const GET_ALL_COLLECTIONS_LOADING = "GET_ALL_COLLECTIONS_LOADING";

export const CREATE_COLLECTIONS = "CREATE_COLLECTIONS";
export const CREATE_COLLECTIONS_LOADING = "CREATE_COLLECTIONS_LOADING";

export const EDIT_COLLECTIONS = "EDIT_COLLECTIONS";
export const EDIT_COLLECTIONS_LOADING = "EDIT_COLLECTIONS_LOADING";

export const DELETE_COLLECTIONS = "DELETE_COLLECTIONS";
export const DELETE_COLLECTIONS_LOADING = "DELETE_COLLECTIONS_LOADING";

export const GET_COLLECTION_BY_ID = "GET_COLLECTION_BY_ID";
export const GET_COLLECTION_BY_ID_LOADING = "GET_COLLECTION_BY_ID_LOADING";

export const GET_NFT_BY_COLLECTION = "GET_NFT_BY_COLLECTION";
export const GET_NFT_BY_COLLECTION_LOADING = "GET_NFT_BY_COLLECTION_LOADING";

export const GET_COLLECTION_LISTINGS = "GET_COLLECTION_LISTINGS";
export const GET_COLLECTION_LISTINGS_LOADING =
  "GET_COLLECTION_LISTINGS_LOADING";

export const GET_OTHER_LISTINGS = "GET_OTHER_LISTINGS";
export const GET_OTHER_LISTINGS_LOADING = "GET_OTHER_LISTINGS_LOADING";

export const GET_COLLECTION_STATS = "GET_COLLECTION_STATS";
export const GET_COLLECTION_STATS_LOADING = "GET_COLLECTION_STATS_LOADING";
