export const CREATE_PETITION = 'CREATE_PETITION';
export const CREATE_PETITION_LOADING = 'CREATE_PETITION_LOADING';

export const GET_ALL_PETITIONS = 'GET_ALL_PETITIONS';
export const GET_ALL_PETITIONS_LOADING = 'GET_ALL_PETITIONS_LOADING';

export const SUBMIT_VOTE = 'SUBMIT_VOTE';
export const SUBMIT_VOTE_LOADING = 'SUBMIT_VOTE_LOADING';

export const GET_PETITION_BY_ID = 'GET_PETITION_BY_ID';
export const GET_PETITION_BY_ID_LOADING = 'GET_PETITION_BY_ID_LOADING';
